name: CI

on:
  push:
    branches: [develop, main]
  pull_request:
    branches: [develop, main]

jobs:
  validate:
    uses: rcorra68/reusable-workflows/.github/workflows/ci.yml@main
    with:
      solution_path: "ActiveDirectory.slnx"
      runs_on: "windows-latest"
      dotnet_version: "9.0.x"